### ISSUE TITLE
javac: invalid flag: --release

### ISSUE THREAD

**Issue by hktalent** [airman604/jdbc-backdoor#1]
```
javac --release 8 oracle/jdbc/OracleDriver.java
javac: invalid flag: --release
Usage: javac <options> <source files>
use -help for a list of possible options
make: *** [oracle/jdbc/OracleDriver.class] Error 2
google:jdbc-backdoor 0x101$ javac  8 oracle/jdbc/OracleDriver.java
javac: invalid flag: 8
Usage: javac <options> <source files>
use -help for a list of possible options
google:jdbc-backdoor 0x101$ javac   oracle/jdbc/OracleDriver.java

```
@Hktalent3135773

**Comment by padi1234** [comment]
![ 147385458 wird hochgeladen...]![ 147385459 wird hochgeladen...]/73397730/147385458-95768a9c-e219-43bf-b1b5-006515e8d121.jpeg)![image](https://user-images.githubusercontent.com/73397730/147385459-24bf0f82-b091-437d-8b37-92eb3d640872.jpeg)![Uploading 147385464@c![image](https://user-images.githubusercontent.com/73397730/147385470-e0ecc91e-ab89-40fd-b4cb-be838d8a2b24.jpeg)...]
